name: Publish Package to NPM
on:
  publish:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - run: |
          echo "node"
          node -v
          echo "pnpm"
          pnpm -v
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "14847208+${{ github.actor }}@users.noreply.github.com"
      - run: pnpm install
      - run: pnpm run new-version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm run new-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
